### ISSUE TITLE
Plugin incompatible with redmine versions over 5.0.2

### ISSUE THREAD

**Issue by g-nardiello** [readyredmine/ready_email_footer#2]
I try to install this plugin in my redmine instance and got the following error:

```
Redmine::PluginRequirementError: ready_email_footer plugin requires a Redmine version between 4.1.0 and 5.0.2 but current is 5.0.4.stable
```

Into `init.rb` file limit redmine compatible version to 5.0.2, but I don't think there are breaking changes. Could you check it and make this plugin compatible with newer redmine 5 versions?

https://github.com/readyredmine/ready_email_footer/blob/3bc5d26b3a46fa65a114c35ac806fae50f942de1/init.rb#L30

I think, if there are no breaking changes, it could be changed to allow all redmine 5 versions:

```
requires_redmine :version => '4.1.0'..'5' 
```

**Comment by 34rc1n** [comment]
Thank you for raising this issue
There is a new release available now which includes the suggested change.
